<?php
/**
 *  @SWG\Definition(
 *          definition="Work",
 *          @SWG\Property(
 *              property="workId",
 *              type="string",
 *              description="作品ID"
 *          ),
 *          @SWG\Property(
 *              property="workTitle",
 *              type="string",
 *              description="作品タイトル"
 *          ),
 *          @SWG\Property(
 *              property="workTitleOrig",
 *              type="string",
 *              description="タイトル原題"
 *          ),
 *          @SWG\Property(
 *              property="saleType",
 *              type="string",
 *              description="販売タイプ（1=sell, 2=rental）"
 *          ),
 *          @SWG\Property(
 *              property="workTypeId",
 *              type="string",
 *              description="アイテム種別"
 *          ),
 *          @SWG\Property(
 *              property="jacketL",
 *              type="string",
 *              description="ジャケ写"
 *          ),
 *          @SWG\Property(
 *              property="saleStartDate",
 *              type="string",
 *              description="レンタル開始日"
 *          ),
 *          @SWG\Property(
 *              property="bigGenreId",
 *              type="string",
 *              description="大ジャンルID"
 *          ),
 *          @SWG\Property(
 *              property="bigGenreName",
 *              type="string",
 *              description="大ジャンル"
 *          ),
 *          @SWG\Property(
 *              property="mediumGenreId",
 *              type="string",
 *              description="中ジャンルID"
 *          ),
 *          @SWG\Property(
 *              property="mediumGenreName",
 *              type="string",
 *              description="中ジャンル"
 *          ),
 *          @SWG\Property(
 *              property="ratingName",
 *              type="string",
 *              description="年齢制限表示"
 *          ),
 *          @SWG\Property(
 *              property="docText",
 *              type="string",
 *              description="説明"
 *          ),
 *          @SWG\Property(
 *              property="createdYear",
 *              type="string",
 *              description="作成年"
 *          ),
 *          @SWG\Property(
 *              property="createdCountries",
 *              type="string",
 *              description="作成国"
 *          ),
 *          @SWG\Property(
 *              property="copyright",
 *              type="string",
 *              description="コピーライト"
 *          )
 *  )
 * */
/**
 *  @SWG\Definition(
 *          definition="Review",
 *          @SWG\Property(
 *              property="rating",
 *              type="number",
 *              format="float",
 *              description="レーティング"
 *          ),
 *          @SWG\Property(
 *              property="contributor",
 *              type="string",
 *              description="投稿者"
 *          ),
 *          @SWG\Property(
 *              property="contributeDate",
 *              type="string",
 *              description="投稿日時"
 *          ),
 *          @SWG\Property(
 *              property="contents",
 *              type="string",
 *              description="内容"
 *          ),
 *  )
 * */
/**
 *  @SWG\Definition(
 *          definition="Product",
 *          @SWG\Property(
 *              property="productName",
 *              type="string",
 *              description="商品名"
 *          ),
 *          @SWG\Property(
 *              property="saleType",
 *              type="string",
 *              description="販売タイプ（1=sell, 2=rental）"
 *          ),
 *          @SWG\Property(
 *              property="productCode",
 *              type="string",
 *              description="商品番号"
 *          ),
 *          @SWG\Property(
 *              property="ccc_family_cd",
 *              type="string",
 *              description="cccファミリーコード"
 *          ),
 *          @SWG\Property(
 *              property="jan",
 *              type="string",
 *              description="JANコード"
 *          ),
 *          @SWG\Property(
 *              property="itemCd",
 *              type="string",
 *              description="アイテムコード"
 *          ),
 *          @SWG\Property(
 *              property="itemName",
 *              type="string",
 *              description="アイテム名"
 *          ),
 *          @SWG\Property(
 *              property="jacketL",
 *              type="string",
 *              description="ジャケ写"
 *          ),
 *          @SWG\Property(
 *              property="saleStartDate",
 *              type="string",
 *              description="発売日"
 *          ),
 *          @SWG\Property(
 *              property="discInfo",
 *              type="string",
 *              description="組数"
 *          ),
 *          @SWG\Property(
 *              property="subtitle",
 *              type="string",
 *              description="字幕"
 *          ),
 *          @SWG\Property(
 *              property="soundSpec",
 *              type="string",
 *              description="音声"
 *          ),
 *          @SWG\Property(
 *              property="regionInfo",
 *              type="string",
 *              description="リージョンコード"
 *          ),
 *          @SWG\Property(
 *              property="priceTaxOut",
 *              type="string",
 *              description="定価（税抜）"
 *          ),
 *          @SWG\Property(
 *              property="playTime",
 *              type="string",
 *              description="収録時間"
 *          ),
 *          @SWG\Property(
 *              property="contents",
 *              type="string",
 *              description="内容"
 *          ),
 *          @SWG\Property(
 *              property="privilege",
 *              type="string",
 *              description="特典内容"
 *          ),
 *          @SWG\Property(
 *              property="bestAlbumFlg",
 *              type="string",
 *              description="ベストアルバムフラグ"
 *          ),
 *          @SWG\Property(
 *              property="makerName",
 *              type="string",
 *              description="メーカー"
 *          ),
 *  )
 * */
/**
 *  @SWG\Definition(
 *          definition="ProductNarrow",
 *          @SWG\Property(
 *              property="productName",
 *              type="string",
 *              description="商品名"
 *          ),
 *          @SWG\Property(
 *              property="cccFamilyCd",
 *              type="string",
 *              description="cccファミリーコード"
 *          ),
 *          @SWG\Property(
 *              property="itemCd",
 *              type="string",
 *              description="アイテムコード"
 *          ),
 *          @SWG\Property(
 *              property="jacketL",
 *              type="string",
 *              description="ジャケ写"
 *          ),
 *          @SWG\Property(
 *              property="saleStartDate",
 *              type="string",
 *              description="発売日"
 *          ),
 *          @SWG\Property(
 *              property="newFlag",
 *              type="string",
 *              description="NEWフラグ"
 *          ),
 *  )
 * */
/**
 *  @SWG\Definition(
 *          definition="WorkNarrow",
 *          @SWG\Property(
 *              property="workId",
 *              type="string",
 *              description="作品ID"
 *          ),
 *          @SWG\Property(
 *              property="workTitle",
 *              type="string",
 *              description="作品タイトル"
 *          ),
 *          @SWG\Property(
 *              property="jacketL",
 *              type="string",
 *              description="ジャケ写"
 *          ),
 *          @SWG\Property(
 *              property="supplement",
 *              type="string",
 *              description="著者・作者"
 *          ),
 *          @SWG\Property(
 *              property="cccProductCd",
 *              type="string",
 *              description="ccc作品コード"
 *          ),
 *          @SWG\Property(
 *              property="saleType",
 *              type="integer",
 *              description="販売タイプ（1=sell, 2=rental） 指定しないと両方取得",
 *          ),
 *  )
 * */
