<?php
/**
 * Created by PhpStorm.
 * User: ayumu
 * Date: 2018/06/12
 * Time: 14:45
 */
return [
    'himo_areas',
//    'himo_awards',
    'himo_countries',
    'himo_devices',
//    'himo_distribution_plans',
//    'himo_distributions',
    'himo_doc_sources',
    'himo_doc_types',
    'himo_docs',
//    'himo_episode_products',
//    'himo_episodes',
    'himo_game_models',
    'himo_genres',
//    'himo_id_link_logs',
//    'himo_id_logs',
    'himo_items',
    'himo_jobs',
    'himo_makers',
    'himo_media_categories',
    'himo_media_formats',
    'himo_people',
//    'himo_person_jobs',
//    'himo_person_keywords',
//    'himo_person_relation_types',
//    'himo_person_relations',
//    'himo_person_tags',
//    'himo_person_trivias',
//    'himo_person_urls',
//    'himo_person_youtubes',
    'himo_product_countries',
    'himo_product_devices',
//    'himo_product_distribution_plans',
    'himo_product_docs',
    'himo_product_genres',
//    'himo_product_keywords',
    'himo_product_people',
    'himo_product_scenes',
    'himo_product_tracks',
//    'himo_product_trailer_urls',
//    'himo_product_trailor_pcs',
    'himo_product_types',
    'himo_products',
//    'himo_products_tmp',
    'himo_ratings',
    'himo_roles',
    'himo_services',
    'himo_big_series',
    'himo_big_series_small_series',
    'himo_small_series',
    'himo_small_series_works',
//    'himo_tags',
    'himo_track_people',
    'himo_tracks',
//    'himo_trailer_urls',
//    'himo_work_awards',
    'himo_work_countries',
    'himo_work_docs',
    'himo_work_episodes',
//    'himo_work_keywords',
    'himo_work_products',
    'himo_work_relations',
    'himo_work_scenes',
//    'himo_work_trailer_urls',
    'himo_work_types',
    'himo_work_works',
    'himo_works',
//    'himo_works_2', // 不要？
    'himo_xmedia_big_series',
    'himo_xmedia_relation_types',
    'himo_xmedias',
];